#ifndef SHAD_H_
#define SHAD_H_

#include <fcntl.h>

#define SHAD_HASH_ALGO MHASH_SHA256
#define SHAD_HASH_BLOCK_SIZE 32

#define SHAD_INPUT_BUFFER_SIZE 2048

#ifndef SHAD_DATA_ATOMICITY
#define SHAD_WRITE_FLAGS O_RDWR | O_APPEND | O_CREAT
#else
#define SHAD_WRITE_FLAGS O_RDWR | O_APPEND | O_SYNC | O_CREAT
#endif

#define SHAD_READ_FLAGS O_RDONLY
#define SHAD_OPEN_MODE S_IRUSR | S_IWUSR | S_IRGRP | S_IWGRP

#endif /* SHAD_H_ */
